[package]
name = "compile_timing_extractor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.18", features = ["derive"]}
regex = "1.11.0"
serde = {version="1.0.210", features = ["derive"]}
serde_json = "1.0.128"
