name: Extract data from build timing html files and perform react deployment

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  linux-ubuntu:
    name: Extract timing information from new build timing html files
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout compile-timings-viewer repo
        uses: actions/checkout@v4
        with:
          repository: debate-map/compile-timings-viewer
          path: compile-timings-viewer

      - name: Create react build from compile-timings-viewer
        working-directory: compile-timings-viewer
        run: |
          yarn install
          yarn run build

      - name: Upload react build artifact
        uses: actions/upload-artifact@v3
        with:
          name: react-build
          path: compile-timings-viewer/dist

      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          path: compile-timings

      - name: Create missing directories & extract JSON out of build timing html(s)
        working-directory: compile-timings
        run: |
          mkdir -p docs/timings/build_metadatas
          mkdir -p docs/timings/build_units
          cd compile_timing_extractor
          cargo run -- -r ../docs/timings/raw_html -t ../docs/timings/tracker.json -m ../docs/timings/build_metadatas/ -u ../docs/timings/build_units

      - name: Download react build artifact
        uses: actions/download-artifact@v3
        with:
          name: react-build
          path: react-build
      - name: Deploy react build
        run: |
          cp -R react-build/* compile-timings/docs/

      - name: Commit and push changes
        working-directory: compile-timings
        run: |
          git config user.name "compile-timings[bot]"
          git config user.email debatemap@gmail.com
          git add docs
          git diff --staged --quiet || {
            git commit -m "[skip ci]: generate JSON from build timing html files"
            git push
          }
